/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spotifymusicgenerator;

import java.io.IOException;
import java.util.*;

import org.apache.hc.core5.http.ParseException;

import com.mashape.unirest.http.exceptions.UnirestException;

import se.michaelthelin.spotify.exceptions.SpotifyWebApiException;

public class App {

    public static void main(String[] args) throws IOException, UnirestException, ParseException, SpotifyWebApiException {
        // makes the user
        Scanner console = new Scanner(System.in);
        
        System.out.println("Enter your CLIENT_ID ");
        String clientID = console.nextLine();
        
        System.out.println("Enter your ClIENT_SECRET ");
        String secret = console.nextLine();

        SpotUser user = new SpotUser(clientID, secret);

        // gets artist and ask for number of songs to use.
        List<String> artist = prompt(console);

        System.out.println("How many songs from each artist?");
        int num = console.nextInt();

        System.out.println("Enter your playlistID ");
        String playListID = console.nextLine();

        // calls on a method to generate a new playlist
        user.makePlayList(artist, num, playListID);

        System.out.println("Finished Playlist check spotify now!");
    }

    // asks users for a list of artists to create a playlist of 
    // and how many songs from each artist
    public static List<String> prompt(Scanner console){
        List<String> result = new ArrayList<>();
        String input = "";

        System.out.println("Enter the artists you'd like to get songs from: Input \"quit\" when you're done");
        System.out.print("Artist or Quit: ");
        input = console.nextLine();
        while(!input.equalsIgnoreCase("quit")){
            result.add(input);
            System.out.print("Artist or Quit: ");
            input = console.nextLine();
        }
        
        return result;
    }
}
